baseURL = 'https://lmcorner.net/'
theme = 'PaperMod'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false # Keeps English at the root (/)

[markup.goldmark.renderer]
    unsafe = true

[languages]
    [languages.en]
        languageCode = 'en-us'
        languageName = 'English'
        contentDir = 'content/en'
        weight = 1
        title = 'The .NET + LM Sandbox'

        [languages.en.params.homeInfoParams]
            Title = "Hello there ✌️"
            Content = "Welcome to the Sandbox. <br> This is where we bridge the gap between .NET and the world of AI (LLMs, SLMs, and beyond). Expect practical C# guides, raw experiments, and a bit of everything else. <br> Glad to have you here!"

        [languages.en.menu]
            [[languages.en.menu.main]]
                name = "News"
                url = "/news"
                weight = 10
            [[languages.en.menu.main]]
                name = "Glossary"
                url = "/glossary"
                weight = 20
            [[languages.en.menu.main]]
                name = "Tags"
                url = "/tags"
                weight = 30

    [languages.ru]
        languageCode = 'ru-ru'
        languageName = 'Русский'
        contentDir = 'content/ru'
        weight = 2
        title = '.NET + Нейросети Песочница'
                
        [languages.ru.params.homeInfoParams]
            Title = "Всем привет ✌️"
            Content = "Рад видеть вас в Песочнице. <br> Здесь мы колдуем с нейросетями (LLM, SLM и всё, что между ними) с помощью .NET, делимся кодом и пробуем нестандартные подходы. <br> Всем добра!"

        [languages.ru.menu]
            [[languages.ru.menu.main]]
                name = "Новости"
                url = "/news"
                weight = 10
            [[languages.ru.menu.main]]
                name = "Глоссарий"
                url = "/glossary"
                weight = 20
            [[languages.ru.menu.main]]
                name = "Тэги"
                url = "/tags"
                weight = 30
[params]
    # This tells PaperMod to show the language switcher
    displayFullLangName = true    
    labelTagName = "#"
    showBreadCrumbs = true
    showReadingTime = true

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/aleksandr-turkin-20a60699/"